[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pftp"
description = 'Python for the People. An intro to Python for people with zero programming experience'
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
keywords = ["python", "beginner"]
authors = [
  { name = "ImAKappa", email = "imaninconsp1cuouskappa@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "zensical",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/ImAKappa/pftp#readme"
Issues = "https://github.com/ImAKappa/pftp/issues"
Source = "https://github.com/ImAKappa/pftp"

[tool.hatch.version]
path = "pftp/__about__.py"

[tool.hatch.envs.default]
python = "3.14"
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
test = "pytest test {args}"
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=pftp --cov=tests {args}"
no-cov = "cov --no-cov {args}"
docs = ""
clippy = "python -m clippy"
pymd = "python -m pftp.pymd {args}"

[[tool.hatch.envs.test.matrix]]
python = ["314"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "pftp/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.extend-per-file-ignores]
"pftp/*" = ["T201"]
"codealongs/*" = [
  "T201", # print debugging
  "PLR2004", # magic values 
  "S311", # cryptographically insecure psudeo-RNG
  "PLC0415", # top-level imports
  "F841", # assigned, but unused variables
]
"docs/.hooks/*" = ["INP001", "T201"]
