[project]
site_name = "Python for the People"
site_url = "https://imakappa.github.io/pftp/"
repo_url = "https://github.com/ImAKappa/pftp/"
repo_name = "ImAKappa/pftp"
site_description = "An introduction to Python for those without any programming experience"
site_author = "ImAKappa"
copyright = "&copy; 2025 ImAKappa"
docs_dir = "docs"
site_dir = "site"

[project.theme]
language = "en"
features = [
    "navigation.indexes",
    "toc.follow",
    "navigation.footer",
]

[project.theme.icon]
logo = "material/snake"
previous = "fontawesome/solid/angle-left"
next = "fontawesome/solid/angle-right"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "purple"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "deep purple"
accent = "green"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"