[project]
site_name = "Python for the People"
site_url = "https://imakappa.github.io/pftp/"
repo_url = "https://github.com/ImAKappa/pftp/"
repo_name = "ImAKappa/pftp"
site_description = "An introduction to Python for those without any programming experience"
site_author = "ImAKappa"
copyright = "&copy; 2025 ImAKappa"
docs_dir = "docs"
site_dir = "site"
extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]
nav = [
    {"Welcome" = "index.md"},
    {"0. Getting Started" = [
        "0-Getting-Started/00_language.md",
        "0-Getting-Started/01_translation.md",
        "0-Getting-Started/02_problem_solving.md",
        "0-Getting-Started/03_tools.md",
    ]},
    {"1. Project: Fortune Telling" = "1-Project-Basics/index.md"},
    {"2. Project: Downloads Folder" = "3-Project-Files/index.md"}
    # {"2. Reading & Writing" = [
    #     "2-Reading-and-Writing/00_reading.md",
    #     "2-Reading-and-Writing/01_reuse.md",
    #     "2-Reading-and-Writing/02_writing.md",
    # ]},
]

[project.theme]
language = "en"
features = [
    "navigation.indexes",
    "toc.follow",
    "navigation.footer",
    "content.tabs.link",
]

[project.theme.icon]
logo = "material/snake"
previous = "fontawesome/solid/angle-left"
next = "fontawesome/solid/angle-right"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "purple"
accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "deep purple"
accent = "green"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
base_path = [
    # 0-Getting-Started
    "./docs/assets/scripts/uselessfact.py",
    # 1-Project-Basics
    "./docs/1-Project-Basics/fortune/fortune_0.py",
    "./docs/1-Project-Basics/fortune/fortune_1.py",
    "./docs/1-Project-Basics/fortune/fortune_2.py",
    "./docs/1-Project-Basics/fortune/fortune_3.py",
    "./docs/1-Project-Basics/fortune/fortune_4.py"
]
check_paths = true
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.attr_list]
