site_name: Python for the People
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.snippets:
      base_path: ["../pftp/scripts", "../pftp/clippy-in-parts"]
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
  - pymdownx.superfences