site_name: Python for the People
theme:
  name: material
  features:
    - content.tabs.link
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
